'use client';
import { AnimatePresence, motion } from 'framer-motion';
import Link from 'next/link';
import React, { useEffect, useState } from 'react';

const AccordionItem = ({
  id,
  title,
  content,
  index,
  isOpen,
  toggleOpen,
}: any) => {
  return (
    <motion.div
      className="border-b border-white/10 last:border-0"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.1 }}
    >
      <button
        onClick={() => toggleOpen(id)}
        className="w-full py-8 flex items-center justify-between text-left group"
      >
        <div className="flex items-center gap-6">
          <span className="text-blue-500 font-bold text-sm bg-blue-500/10 w-10 h-10 rounded-xl flex items-center justify-center border border-blue-500/20 group-hover:bg-blue-500 group-hover:text-white transition-all duration-300">
            {(index + 1).toString().padStart(2, '0')}
          </span>
          <h2 className="text-2xl font-bold text-white group-hover:text-blue-400 transition-colors duration-300">
            {title}
          </h2>
        </div>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          className="text-white/30 group-hover:text-blue-500 transition-colors"
        >
          <svg
            className="w-6 h-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="19 9l-7 7-7-7"
            />
          </svg>
        </motion.div>
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div className="pb-8 pt-2 pl-16 text-white/60 text-lg leading-relaxed font-light">
              {content}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const AirQoDataPage = () => {
  const [openSection, setOpenSection] = useState<string | null>('intro');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.documentElement.style.scrollBehavior = 'smooth';
    }
  }, []);

  const toggleOpen = (id: string) => {
    setOpenSection(openSection === id ? null : id);
  };

  const sections = [
    {
      id: 'intro',
      title: 'Introduction',
      content: (
        <p className="text-justify">
          Welcome to Octasence! These Data Terms govern your access to and use
          of the infrastructure intelligence and sensory data provided by
          Octasence. By accessing or using our data, or by utilizing Octasence
          integrated devices, you agree to be bound by these protocols. Our
          mission is to provide transparent, high-fidelity environmental and
          infrastructure data for the global community.
        </p>
      ),
    },
    {
      id: 'license',
      title: 'General Data Use',
      content: (
        <div className="space-y-4 text-justify">
          <p>
            The open-access data provided by Octasence is licensed under the
            Creative Commons{' '}
            <a
              href="https://creativecommons.org/licenses/by/4.0/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-400 hover:underline"
            >
              Attribution 4.0 International License (CC BY 4.0)
            </a>
            .
          </p>
          <p>
            This allows you to share and adapt the material for any medium,
            provided you give appropriate credit to Octasence and indicate if
            changes were made.
          </p>
          <p className="text-blue-400 font-semibold italic">
            Non-Commercial restriction: Prior written permission is required for
            any commercial exploitation of granular or raw data streams.
          </p>
        </div>
      ),
    },
    {
      id: 'device-datarights',
      title: 'Device & Data Rights',
      content: (
        <div className="space-y-4 text-justify">
          <p>
            When utilizing Octasence hardware, you retain co-ownership rights
            over the data generated by those specific nodes. This includes the
            right to access raw data for internal research and personal
            analysis.
          </p>
          <p>
            Simultaneously, you grant Octasence a global, royalty-free license
            to host, aggregate, and process this data to enhance our predictive
            models and public health research, provided that personal
            identifiers are strictly anonymized.
          </p>
        </div>
      ),
    },
    {
      id: 'fair-use',
      title: 'Fair Use & Fair Access',
      content: (
        <div className="space-y-4 text-justify">
          <p>
            To ensure the integrity of the Octasence network, we implement
            automated rate limiting. We reserve the right to throttle or suspend
            access for entities engaged in malicious scraping, excessive API
            requests, or any activity that degrades the service for the global
            community.
          </p>
        </div>
      ),
    },
    {
      id: 'restrictions',
      title: 'Restrictions',
      content: (
        <ul className="list-disc pl-6 space-y-2 text-justify">
          <li>
            <strong>No Endorsement</strong>: You may not imply that Octasence
            endorses your research or products without distinct written consent.
          </li>
          <li>
            <strong>No Data Scraping</strong>: Automated harvesting that
            circumvents our API protocols is strictly prohibited.
          </li>
          <li>
            <strong>No Commercial Resale</strong>: Reselling Octasence data as a
            primary product or service is not permitted under the open license.
          </li>
        </ul>
      ),
    },
    {
      id: 'disclaimer',
      title: 'Disclaimer',
      content: (
        <p className="text-justify">
          Octasence provides data &quot;as is&quot;. While we strive for extreme
          precision through AI-driven calibration, we do not guarantee the
          perpetual accuracy or availability of real-time data streams. Use of
          this data for critical decision-making is at the user&apos;s own risk.
        </p>
      ),
    },
    {
      id: 'contact',
      title: 'Contact Information',
      content: (
        <div className="space-y-6">
          <p>
            For specialized data requests, commercial licensing, or technical
            inquiries regarding our data protocols, please contact our
            intelligence team.
          </p>
          <div className="mt-4">
            <Link
              href="/contact"
              className="inline-flex items-center px-6 py-2.5 bg-blue-600 hover:bg-blue-500 text-white text-sm font-bold rounded-lg transition-all active:scale-95 shadow-lg shadow-blue-500/20"
            >
              Contact Data Team
            </Link>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className="w-full min-h-screen octa-shell pb-20 pt-8 selection:bg-blue-500/30 overflow-hidden">
      {/* Background Decor */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-[-10%] right-[-10%] w-[50%] h-[50%] bg-blue-500/5 blur-[120px] rounded-full" />
        <div className="absolute bottom-[-10%] left-[-20%] w-[60%] h-[60%] bg-blue-500/5 blur-[140px] rounded-full animate-pulse" />
      </div>

      {/* Hero Section */}
      <div className="max-w-4xl mx-auto px-6 mb-8 text-center relative z-10">
        <motion.div
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="octa-heading text-4xl md:text-6xl mb-2 leading-tight tracking-tighter">
            Octasence <span className="octa-accent-text">Data Policy</span>
          </h1>
          <p className="text-white/50 text-lg font-light max-w-2xl mx-auto">
            Governance framework for infrastructure intelligence and sensory
            data.
          </p>
        </motion.div>
      </div>

      {/* Accordion Layout */}
      <motion.main className="max-w-4xl mx-auto px-6 relative z-10">
        <div className="space-y-2">
          {sections.map((section, idx) => (
            <AccordionItem
              key={section.id}
              {...section}
              index={idx}
              isOpen={openSection === section.id}
              toggleOpen={toggleOpen}
            />
          ))}
        </div>
      </motion.main>
    </div>
  );
};

export default AirQoDataPage;
